# -*- coding: utf-8 -*-
"""Task09-optional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZeBlE3RbC3VU6iaWJ_pXhjnYygWIrhaZ

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Spanish: Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos.

English: Search for individuals in both graphs and link them using the OWL:sameAs property; insert these matches into g3. We consider two individuals to be the same if they have the same first name and surname. Please note that the URIs do not necessarily have to be the same for the same individual in both graphs.
"""

from rdflib.namespace import RDF
#First we examine how the classes are defined to see the Person class definition
print("Classes in g1:")
for s,p,o in g1.triples((None, RDF.type, None)):
    print(s, o)

print("\nClasses in g2:")
for s,p,o in g2.triples((None, RDF.type, None)):
    print(s, o)

OWL = Namespace("http://www.w3.org/2002/07/owl#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
data3 = Namespace("http://data.three.org#")
data4 = Namespace("http://data.four.org#")

for s, p, o in g1.triples((None, RDF.type, data3.Person)):
    given1 = g1.value(s, VCARD.Given)
    family1 = g1.value(s, VCARD.Family)

    for s2, p2, o2 in g2.triples((None, RDF.type, data4.Person)):
      given2 = g2.value(s2, VCARD.Given)
      family2 = g2.value(s2, VCARD.Family)
      if (given1 == given2 and family1 == family2):
            g3.add((s, OWL.sameAs, s2))
            g3.add((s2, OWL.sameAs, s))

for s,p,o in g3.triples((None, None, None)):
    print(s,p,o)