# -*- coding: utf-8 -*-
"""Task08-optional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVr3kDGoz7L-bBRAAr4fv5k30B3Nl-4I

**Task 08: Completing missing data**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Spanish: Lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas.

English: List all the elements of the Person class in the first graph (data01.rdf) and fill in any missing fields (given name, family name and email) using the data from the second graph (data02.rdf). You can use SPARQL queries or iterate through the graph, or both.
"""

from rdflib.namespace import RDF, RDFS
vcard_rdf = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
g1.bind("vcard-rdf", vcard_rdf)
dorg = Namespace("http://data.org#")
g1.bind("dorg", dorg)

ind = list(g1.subjects(RDF.type, dorg.Person))
# List all elements of the Person class
for i in ind:
  print(i)

props_add = [vcard_rdf.Given, vcard_rdf.Family, vcard_rdf.EMAIL]

# Iterate on the individuals on g1
for i in ind:
  # Properties from props_add
  for pr in props_add:
    # For every value that the property has
    for valor_pr in g2.objects(i,pr):
      g1.add((i,pr,valor_pr))