# -*- coding: utf-8 -*-
"""Task09-optional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WF66s62aBK9sMRuD6RcJR0A4wy2x72I

**Task 09: Data linking**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""*Spanish*: Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos.

English: Search for individuals in both graphs and link them using the OWL:sameAs property; insert these matches into g3. We consider two individuals to be the same if they have the same first name and surname. Please note that the URIs do not necessarily have to be the same for the same individual in both graphs.
"""

whole_graph =  g1+g2
query = """
PREFIX vcard: <http://www.w3.org/2001/vcard-rdf/3.0#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {?persona1 owl:sameAs ?persona2}
WHERE {
  ?persona1 vcard:Given ?fname .
  ?persona1 vcard:Family ?sname .
  ?persona2 vcard:Given ?fname .
  ?persona2 vcard:Family ?sname .
  FILTER (?persona1 != ?persona2)
}
"""
g3+= whole_graph.query(query)

# Check results
for s, p, o in g3:
    print(f"{s} owl:sameAs {o}")