# -*- coding: utf-8 -*-
"""Task09-optional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/FacultadInformatica-LinkedData/Curso2026-2027-ODKG/blob/master/Assignment4/course_materials/notebooks/Task09-optional.ipynb

**Task 09: Data linking**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Spanish: Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos.

English: Search for individuals in both graphs and link them using the OWL:sameAs property; insert these matches into g3. We consider two individuals to be the same if they have the same first name and surname. Please note that the URIs do not necessarily have to be the same for the same individual in both graphs.
"""

FOAF = Namespace("http://xmlns.com/foaf/0.1/")
OWL = Namespace("http://www.w3.org/2002/07/owl#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#") # Define vcard-rdf namespace

# Extract individuals from g1 with their first name and surname
individuals_g1 = {}
for s, p, o in g1.triples((None, VCARD.Given, None)):
    first_name = str(o)
    found_surname = False
    for s2, p2, o2 in g1.triples((s, VCARD.Family, None)):
        surname = str(o2)
        individuals_g1[(first_name, surname)] = s
        found_surname = True
        break

# Extract individuals from g2 with their first name and surname
individuals_g2 = {}
for s, p, o in g2.triples((None, VCARD.Given, None)):
    first_name = str(o)
    found_surname = False
    for s2, p2, o2 in g2.triples((s, VCARD.Family, None)):
        surname = str(o2)
        individuals_g2[(first_name, surname)] = s
        found_surname = True
        break

# Find common individuals and link them in g3
for (first_name, surname), uri1 in individuals_g1.items():
    if (first_name, surname) in individuals_g2:
        uri2 = individuals_g2[(first_name, surname)]
        g3.add((uri1, OWL.sameAs, uri2))

# Print the triples in g3
print("Triples in g3 (owl:sameAs links):")
for s, p, o in g3:
    print(f"{s} {p} {o}")