# -*- coding: utf-8 -*-
"""Task08-optional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/FacultadInformatica-LinkedData/Curso2026-2027-ODKG/blob/master/Assignment4/course_materials/notebooks/Task08-optional.ipynb

**Task 08: Completing missing data**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Spanish: Lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas.

English: List all the elements of the Person class in the first graph (data01.rdf) and fill in any missing fields (given name, family name and email) using the data from the second graph (data02.rdf). You can use SPARQL queries or iterate through the graph, or both.
"""

# First part with SPARQL
query = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX vcard-rdf: <http://www.w3.org/2001/vcard-rdf/3.0#>
PREFIX ex: <http://data.org#>

SELECT ?s ?gn ?fn ?em
WHERE {
    ?s rdf:type ex:Person .
    OPTIONAL { ?s vcard-rdf:Given ?gn . }
    OPTIONAL { ?s vcard-rdf:Family ?fn . }
    OPTIONAL { ?s vcard-rdf:EMAIL ?em . }
}
"""

# Execute the query on g1
for r in g1.query(query):
  print(r)

# Second one through iteration
# Namespaces for g2
FOAF = Namespace("http://xmlns.com/foaf/0.1/")
SCHEMA = Namespace("http://schema.org/")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

combined_people_data = {}

for s, gn, fn, em in g1.query(query):
    person_uri = str(s)
    current_gn = str(gn) if gn else None
    current_fn = str(fn) if fn else None
    current_em = str(em) if em else None

    if not current_gn:
        gn_from_g2 = g2.value(URIRef(person_uri), VCARD.Given)
        if gn_from_g2: current_gn = str(gn_from_g2)

    if not current_fn:
        fn_from_g2 = g2.value(URIRef(person_uri), VCARD.Family)
        if fn_from_g2: current_fn = str(fn_from_g2)

    if not current_em:
        em_from_g2 = g2.value(URIRef(person_uri), VCARD.EMAIL)
        if em_from_g2: current_em = str(em_from_g2)

    combined_people_data[person_uri] = {
        "givenName": current_gn,
        "familyName": current_fn,
        "email": current_em
    }

# Print the results
for person_uri, data in combined_people_data.items():
    print(f"Person URI: {person_uri}")
    print(f"  Given Name: {data['givenName']}")
    print(f"  Family Name: {data['familyName']}")
    print(f"  Email: {data['email']}")